printer3d_manager:
  ros__parameters:
    history_file_dir: "/home/gulltor/Ramsai_Robotics/history/test_retraction"
    gcode_file_dir: "/home/gulltor/Ramsai_Robotics/Gcodes/impression_piece_ecroulement.gcode"